### PR TITLE
MNT Target the next minor branches

### PR DESCRIPTION
**Pull request by maxime-rainville**

### CODE REVIEW

**Review by emteknetnz — APPROVED** [review]
MOG

**Comment by maxime-rainville** [comment]
I sincerely doubt it's going to be green, but we will not know for sure what's broken until we merge it.

**Comment by emteknetnz** [comment]
MOR then :-)

**Comment by maxime-rainville** [comment]
Red is the new Green.

**Comment by maxime-rainville** [comment]
As foretold, the build is red. But we'll merge any way as it's better to know what's failing.

**Pull request merged**
