### PR TITLE
Add frameworktest (fixes #12)

### LINKED ISSUE #12: Add frameworktest?
I noticed https://github.com/silverstripe/cwp-recipe-kitchen-sink doesn’t include https://github.com/silverstripe/silverstripe-frameworktest. Which is fine in terms of release testing since it’s not a supported module. But it also means you’ll likely miss certain variations in your testing, for example having a ModelAdmin with enough records to show pagination, or having readonly and disabled versions of all form fields. I’m trying to get OSSers using the kitchen sink as their baseline as well, and they’re already using frameworktest. Any reason we can’t add it?

### PR DESCRIPTION
**Pull request by chillu**

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Well... Every test is failing:

`Multiple classes ("SilverStripe\Widgets\Tests\WidgetControllerTest\TestPage", "SilverStripe\FrameworkTest\Model\TestPage") map to the same table: "TestPage"`.

**Comment by chillu** [comment]
Derp derp. I've renamed the frameworktest table name in https://github.com/silverstripe/silverstripe-frameworktest/pull/53, and ran the `framework` tests locally - @ScopeyNZ  can you merge this other PR and kick off the tests again please?

**Comment by ScopeyNZ** [comment]
I would if I could. It appears that's a core repo. FWIW I've approved the other PR 🙂

**Comment by ScopeyNZ** [comment]
Thanks Ingo. The failures are all currently expected 😧 .

**Pull request merged**
